export const FABRIC_SUGGESTIONS: string[] = [
  '100% Cotton',
  '100% Cotton Denim',
  '100% Linen',
  '100% Linen Single Jersey',
  '1x1 Rib',
  '2x2 Rib',
  '2thread Fleece',
  '3thread Fleece',
  '4 Way Lycra',
  '2 Way Lycra',
  '6 Thread Single Jersey',
  'Acrylic Jute',
  'Acrylic Wool',
  'Acid Wash Denim',
  'Air Mesh',
  'Ajrak',
  'Aloe Vera',
  'Alpaca Wool',
  'Amigurumi Crochet',
  'Aari',
  'Aron Crochet',
  'Bamboo',
  'Bamboo Cotton Lycra',
  'Bamboo Lyocell',
  'Bamboo Terry',
  'Bagru Print',
  'Banjara',
  'Batik',
  'Belgian Linen',
  'Bembar Satin 200',
  'Bird’s Eye Linen',
  'Blackout',
  'Blackwork',
  'Blended Linen',
  'Bobblinet',
  'Bonded Suede',
  'Bonded Velvet',
  'Boskey',
  'Bosnian Crochet',
  'Brasso Pure',
  'Bridal Lace Net',
  'Brocade',
  'Brown Laminated',
  'Bruges Crochet',
  'Bull Denim',
  'Bullion Crochet',
  'Burlap Jute',
  'Butterfly Knit',
  'Butterfly Net',
  'Cambric',
  'Cambric Linen',
  'Cambric Print',
  'Cambric 60x60',
  'Camel',
  'Canvas',
  'Cashmere',
  'Chambray',
  'Chambers Fabrics',
  'Chamundi Chiffon',
  'Chanderi',
  'Chanderi Print',
  'Chemical Nets',
  'Chiffon',
  'Chiffon CC 40gm',
  'Chiffon CC 60gm',
  'Chiffon CXC',
  'Chiffon Diamond 32gm',
  'Chiffon Liba',
  'Chiffon Maharani 24gm',
  'Chiffon Rajni 21gm',
  'Chiffon Shahzadi 36',
  'Chikankari',
  'Chinese Hessian Jute',
  'Chinon',
  'Chinon 36',
  'Chinon 44',
  'Chinon Conv Viscose',
  'Clamshell Knit',
  'Clones Lace Crochet',
  'Coated Denim',
  'Coloured Denim',
  'Cordura Nylon',
  'Corduroy',
  'Corduroy 6/8/11/19/21/23/26 Wales',
  'Corduroy 9/11/14/16 Wales',
  'Corn',
  'Cotton',
  'Cotton Canvas',
  'Cotton Crepe',
  'Cotton Crochet',
  'Cotton Fleece',
  'Cotton Jute',
  'Cotton Linen',
  'Cotton Lycra',
  'Cotton Lycra Polyester',
  'Cotton Lycra Slub',
  'Cotton Lycra Twill',
  'Cotton Matty',
  'Cotton Mesh',
  'Cotton Nets',
  'Cotton Pique',
  'Cotton Print',
  'Cotton Rex Dobby',
  'Cotton Satin',
  'Cotton Silk',
  'Cotton Sinker',
  'Cotton Slub',
  'Cotton Terry',
  'Cotton Transfer Jersey',
  'Cotton Velvet',
  'Crepe',
  'Crepe 40gm',
  'Crepe 54"',
  'Crepe Colour 60',
  'Crepe N.B. 60gm',
  'Crepe Rasgulla Nylon',
  'Crepe Rinkle 60gm',
  'Crepe Self',
  'Crepe Sunfil',
  'Crepe Sunfil 80gm',
  'Crochet Nets',
  'Crinoline',
  'Crinkle Satin 60gm',
  'Crushed Denim',
  'Cutdana',
  'Cutwork',
  'D. Dayna Chiffon',
  'Damask Linen',
  'Darlexx',
  'Dark Indigo Denim',
  'Dark Jute',
  'Denim',
  'Denim Shirt Fabrics',
  'Diamond Knit',
  'Digital Printed Fabric',
  'Dobby',
  'Dobby Towel',
  'Dot Net',
  'Down',
  'Drill',
  'Dry Fit',
  'Duck 10x06',
  'Duck 16x12 / 108x56',
  'Duplan',
  'Duplan C*C 90gm',
  'Duplon Silk C*C 60',
  'Dupian',
  'EcoVero',
  'Ecru Denim',
  'English Net',
  'Embroidered Net',
  'Eucalyptus Cotton',
  'European Linen',
  'eVENT',
  'Faux Fur',
  'Faux Georgette Crochet',
  'Fiberglass Mesh',
  'Filafil',
  'Filet Crochet',
  'Filet Net',
  'Fishnet',
  'Flat Chiffon 40gm',
  'Flat Chiffon 50gm',
  'Flannel',
  'Fleece',
  'Flock Fur',
  'Flock Jute',
  'Flock Velvet',
  'Floral Print',
  'Flower Nets',
  'Foil Mesh Net',
  'French Linen',
  'French Net',
  'French Terry',
  'Front Knitted',
  'Full Feeder',
  'Fur',
  'Gabadian',
  'Georgette',
  'Georgette Foil',
  'Georgette Mukesh 40gm',
  'Georgette Mukesh 60gm',
  'Georgette Print',
  'Gingham',
  'Giza',
  'Glass Towelling Linen',
  'Golden Lurex',
  'Gore-Tex',
  'Gota Pati',
  'Greige Canvas',
  'Greige Chiffon',
  'Greige Cotton Crepe',
  'Greige Corduroy',
  'Greige Georgette',
  'Greige Jute',
  'Greige Khadi',
  'Greige Linen',
  'Greige Modal',
  'Greige Muslin',
  'Greige Organdy',
  'Greige Poplin',
  'Greige Rayon',
  'Greige Silk',
  'Greige Tissue',
  'Greige Velvet',
  'Hakuba',
  'Half Chiffon BTS 44',
  'Handblock Fabric',
  'Handblock Printed',
  'Hand Crochet Dish',
  'Handloom Crochet',
  'Hard Net',
  'Hairpin Crochet',
  'Hemp',
  'Hemp Jute',
  'Herringbone Knit',
  'Hessian',
  'Hex Mesh',
  'Honeycomb',
  'Honeycomb Towel',
  'Holland Linen',
  'Holland Nets',
  'Ice Crushed',
  'Ikat',
  'Ikkat',
  'Imported Satin',
  'Industrial Net',
  'Interlock',
  'Interlocking Knit',
  'Irish Linen',
  'Jacquard',
  'Jacquard Denim',
  'Jacquard Nets',
  'Jacquard Terry',
  'Japanese Linen',
  'Jute',
  'Jute Felt',
  'Jute Flex',
  'Kala Cotton',
  'Kalamkari',
  'Kantha',
  'Kantha Print',
  'Kasab',
  'Kashmiri',
  'Kenaf',
  'Khadi',
  'Khadi Matty',
  'Khakhi',
  'Kinkhab Silk',
  'King Roma Zuric',
  'Knitted Denim',
  'Lace Crochet',
  'Lace Jersey',
  'Lace Sequin',
  'Laminated',
  'Laminated Jute',
  'Lawn',
  'Leather',
  'Lichi Silk',
  'Linen',
  'Linen Checks',
  'Linen Cotton',
  'Linen Flex',
  'Linen Jute',
  'Linen Silk',
  'Linen Slub',
  'Linen Terry',
  'Linens',
  'Loosely Woven Linen',
  'Luthier',
  'Lycra Mesh',
  'Lycra Nets',
  'Lycra Satin',
  'Lycra Spandex',
  'Lycra Suede',
  'Lycra Velvet',
  'Lyocell',
  'M-30 & Rat Chiffon',
  'M-40 Silk',
  'M-60 Silk 700',
  'M-75 Silk 940',
  'Maharani Net',
  'Maheshwari',
  'Maline',
  'Manila Hemp Jute',
  'Marble Denim',
  'Marble Print',
  'Mash Crepe 60gm',
  'Mashru Silk',
  'Matty',
  'Metallic Net',
  'Merino Wool',
  'Mesh',
  'Micro Cotton',
  'Micro Fiber',
  'Micro Satin',
  'Modal',
  'Modal Chanderi Print',
  'Modal Lycra',
  'Modal Satin Print',
  'Moss Crepe',
  'Mouse Knit',
  'Mud Silk',
  'Mukesh Dayna Chiffon 40gm',
  'Mulmul',
  'Munga Georgette',
  'Munga Silk',
  'Muslin',
  'Muslin Print',
  'Natural Linen',
  'Net',
  'Net/Mesh Jute',
  'Neoprene',
  'Nirmal Net',
  'Non-Denim',
  'Non-Laminated Jute',
  'Non-Woven',
  'NS Dull',
  'NS Lycra',
  'Nylon',
  'Nylon Crepe',
  'Nylon Mesh',
  'Nylon Net Crochet',
  'Oil Cloth',
  'Organic',
  'Organic Cotton',
  'Organic Cotton Jute',
  'Organic Cotton Lycra',
  'Organic Cotton Print',
  'Organic Denim',
  'Organic Linen',
  'Organic Luxe',
  'Organic Print',
  'Organza',
  'Organza Print',
  'Organdy',
  'Oxford Checks',
  'Parachute',
  'PC Fleece',
  'PC Matty',
  'PC Shirting',
  'PC Twill',
  'PEVA',
  'Peanut',
  'Pearl Knitting',
  'Pearl Net',
  'Pintex Cotton',
  'Plain Jute',
  'Plain-Woven Linen',
  'Poly Cotton',
  'Poly Linen',
  'Poly Spandex',
  'Poly Voile',
  'Polyester',
  'Polyester Fleece',
  'Polyester Jute',
  'Polyester Net',
  'Polyester Ripstop',
  'Ponte',
  'Popcone',
  'Poplin',
  'Poplin 40x40',
  'Poplin 92x88',
  'Poplin 40x40 / 100x92',
  'Poplin 40x40 / 124x64',
  'Poplin 40x40 / 132x72',
  'Poplin Print',
  'Power Mesh',
  'Printed Blackout',
  'Printed Corduroy',
  'Printed Suede',
  'Printed Velvet',
  'PU Coated',
  'PUL',
  'Pure Silk Brocade',
  'PVC',
  'Qmonos',
  'Quilted Velvet',
  'Rabbit Fur',
  'Ramie',
  'Raschel Crochet',
  'Raw Denim',
  'Raw Silk',
  'Raw Silk Colour Mix 53gm',
  'Raw Silk H/L White 95gm',
  'Raw Silk White 60gm',
  'Rayon',
  'Rayon 120gram',
  'Rayon 140gram',
  'Rayon 150gram',
  'Rayon 160gram',
  'Rayon 170gram',
  'Rayon Crepe',
  'Rayon Linen',
  'Rayon Print',
  'Recycled Cotton',
  'Recycled Denim',
  'Recycled Polyester',
  'Rexin',
  'Reversible Cable Knit',
  'Reversible Net',
  'Reverse Denim',
  'Rib',
  'Roma',
  'RPET',
  'Russian Netting',
  'Sackcloth Canvas',
  'Sandwitch Mesh',
  'Santoor',
  'Satin',
  'Satin 350TC',
  'Satin 400TC',
  'Satin Dyeable 54"',
  'Satin Denim',
  'Satin Jacquard',
  'Satin Print',
  'Satin Stripe',
  'Scoby Leather',
  'Sequin',
  'Sequin Net',
  'Semo Satin',
  'Semo Satin 40',
  'Semo Satin 80gm',
  'Semo Satin 150gm',
  'Serina',
  'Shantoon',
  'Sheer Fabric',
  'Sheeting Linen',
  'Sheeting 16x16',
  'Sheeting 20\'s',
  'Sheeting 30\'s',
  'Sheeting 34x34',
  'Sheep Wool',
  'Shibori',
  'Shimmer',
  'Silk',
  'Silk Banglore 60gm',
  'Silk Banglore Plain 60gm',
  'Silk Crochet',
  'Silk Jute',
  'Silk Nets',
  'Silk Organza',
  'Silk Organza 54"',
  'Silk Organza 2x2',
  'Silk Organza CM',
  'Silk Velvet Plain 180gm',
  'Silk Wool',
  'Single Jersey',
  'Sinker',
  'Sisal Blend',
  'Slub Denim',
  'Soft Net',
  'Soybean',
  'Spandex',
  'Spandex Mesh',
  'Spun Cotton',
  'Spun Matty',
  'Spun Plain 70gm',
  'Star Stitch Knit',
  'Stone Wash Denim',
  'Stretch Denim',
  'Suede',
  'Super Pile',
  'Super Soft',
  'Swimming Lycra',
  'Taby Silk 36"',
  'Taby Silk 44" 20gm',
  'Taffeta',
  'Taslan',
  'Teflon',
  'Terry',
  'Terry Denim',
  'Terry Rayon',
  'Terry Towel',
  'Terry Wool',
  'Thermal',
  'Tissue',
  'Toweling',
  'TR',
  'TR Stretch Denim',
  'TPU',
  'Tulle',
  'Tweed',
  'Twill',
  'Twill 20\'s',
  'Twill 30\'s',
  'Twill Terry',
  'Upholstery',
  'Vegetable Tanned Leather',
  'Velvet',
  'Velvet Quilted',
  'Vinyl',
  'Viscose',
  'Viscose Georgette',
  'Viscose Georgette BTS',
  'Viscose Georgette NB',
  'Viscose Lycra',
  'Voil',
  'Voil 76x68',
  'Voil 80x72',
  'Voil 92x80',
  'Voil 100x100',
  'Waffle',
  'Waffle Towel',
  'Wash Jute',
  'Washable Linen',
  'Waterproof Canvas',
  'Waterproof Nylon',
  'Waxed Cotton',
  'White Velvet Viscose',
  'Wool',
  'Wool Blend Jute',
  'Wool Jute',
  'Woolen',
  'Woolen Knit',
  'Woolen Silk',
  'Woolen Terry',
  'Woolen TR',
  'Woolen Tweed',
  'Yak Wool',
  'Yarn Dyed',
  'Zig Zag Knit',
  'Zuric',
];
